fix: Update acceptance-tests.yml

diff --git a/.github/workflows/acceptance-tests.yml b/.github/workflows/acceptance-tests.yml
--- a/.github/workflows/acceptance-tests.yml
+++ b/.github/workflows/acceptance-tests.yml
@@ -1,6 +1,3 @@
-# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
-# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
-
 name: Acceptance Tests
 
 on:
@@ -9,13 +6,11 @@ on:
       - main
       - master
 
-# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
 permissions:
   contents: read
   pages: write
   id-token: write
 
-# Allow one concurrent deployment
 concurrency:
   group: 'pages'
   cancel-in-progress: true
@@ -56,10 +51,15 @@ jobs:
           MAILINATOR_DOMAIN: ${{secrets.MAILINATOR_DOMAIN}}
       - name: Setup Pages
         uses: actions/configure-pages@v3
+      - name: Check artifact directory
+        run: |
+          if [ ! -d "./test/output/allure" ]; then
+            echo "Artifact directory not found. Exiting."
+            exit 1
+          fi
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          # Upload repository
           path: './test/output/allure'
       - name: Deploy to GitHub Pages
         id: deployment
